name: Deploy server code to server.

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -e "${{secrets.DEPLOY_SSH_KEY}}" > key
          chmod 600 key
          ssh john@iot.2e0byo.co.uk \
           -o StrictHostKeyChecking=no \
           -i key \
           "cd air-sensor && git pull && systemctl --user restart air-sensor"
