name: Deploy server code to server.

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ssh john@iot.2e0byo.co.uk \
           -i <(echo ${{secrets.DEPLOY_SSH_KEY}})\
           "cd air-sensor && git pull && systemctl --user restart air-sensor"
